#pragma once

#include <java/lang/Object.hpp>
#include <java/lang/String.hpp>
#include <java/lang/Class.hpp>
#include <java/lang/Boolean.hpp>
#include <java/lang/Byte.hpp>
#include <java/lang/Character.hpp>
#include <java/lang/Short.hpp>
#include <java/lang/Integer.hpp>
#include <java/lang/Long.hpp>
#include <java/lang/Float.hpp>
#include <java/lang/Double.hpp>
#include <java/nio/Buffer.hpp>
#include <java/nio/ByteBuffer.hpp>
#include <java/nio/CharBuffer.hpp>
#include <java/nio/ShortBuffer.hpp>
#include <java/nio/IntBuffer.hpp>
#include <java/nio/LongBuffer.hpp>
#include <java/nio/FloatBuffer.hpp>
#include <java/nio/DoubleBuffer.hpp>

using java::lang::Object;
using java::lang::Boolean;
using java::lang::Byte;
using java::lang::Character;
using java::lang::Short;
using java::lang::Integer;
using java::lang::Long;
using java::lang::Float;
using java::lang::Double;
using java::lang::Class;
using java::lang::String;
using java::nio::Buffer;
using java::nio::ByteBuffer;
using java::nio::CharBuffer;
using java::nio::ShortBuffer;
using java::nio::IntBuffer;
using java::nio::LongBuffer;
using java::nio::FloatBuffer;
using java::nio::DoubleBuffer;
